# Generated by Django 4.2.7 on 2023-12-02 03:58

from django.db import migrations


def teacher_and_student(apps, schema_editor):
    Teacher = apps.get_model('school', 'Teacher')
    Student = apps.get_model('school', 'Student')

    for student in Student.objects.all():
        teacher = Teacher.objects.get(id=student.teacher_id)
        student.teachers.add(teacher)

class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_student_teachers'),
    ]

    operations = [
        migrations.RunPython(teacher_and_student, )
    ]
