# Generated by Django 4.2.7 on 2023-12-02 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_auto_20231202_0658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='teacher',
        ),
    ]
