# Generated by Django 4.2.7 on 2023-12-02 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_remove_student_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='teachers',
            new_name='teacher',
        ),
    ]
