# Generated by Django 4.2.7 on 2023-12-02 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_rename_teachers_student_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='teacher',
            new_name='teachers',
        ),
    ]
